# Generated by Django 4.2.1 on 2023-05-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0002_user_firt_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.specialty'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.university'),
        ),
    ]
