# Generated by Django 4.2.1 on 2023-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag'),
        ('accounts', '0005_rename_firt_name_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
